import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowDownLeft, ArrowUpRight, Bot, Check, ChevronDown, CircleDot, Code2, ExternalLink, FileCode2, FileText, GitBranch, Github, Layers3, Loader2, LockKeyhole, Maximize2, Play, Radio, Search, ShieldCheck, Square, Terminal, Workflow, X } from 'lucide-react';
import { api, artifactUrl, hosted, previewUrl, stop, token } from './api';
import './styles.css';

const roles = [
  { id: 'boss', number: '01', name: 'The Boss', role: 'Direction & decisions', icon: GitBranch, description: 'Assigns the mission, reviews evidence, and sends work back when it is not ready.' },
  { id: 'researcher', number: '02', name: 'Researcher', role: 'Find the demand', icon: Search, description: 'Reads real job postings and finds preferred capabilities and desired outcomes, with verifiable source excerpts.' },
  { id: 'architect', number: '03', name: 'Architect', role: 'Define the proof', icon: FileText, description: 'Writes a Markdown build brief and acceptance tests for every application.' },
  { id: 'builder', number: '04', name: 'Builder', role: 'Make it work', icon: Code2, description: 'Builds every brief, tests the actual controls in a browser, and repairs failures.' },
  { id: 'supervisor', number: '05', name: 'Supervisor', role: 'Keep everyone honest', icon: ShieldCheck, description: 'Checks worker activity and artifacts throughout the run, reporting progress and problems to the boss.' },
];
const initialGoal = 'Find what employers want from frontend and product engineers. Build practical interactive applications that demonstrate their preferred skills and business outcomes.';
const label = value => (value || 'idle').replaceAll('_', ' ');
const time = date => new Date(date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
function Badge({ value }) { return <span className={`badge ${value || 'idle'}`}><i />{label(value)}</span>; }
function Empty({ icon: Icon = Layers3, title, children }) { return <div className="empty"><Icon size={27}/><h3>{title}</h3><p>{children}</p></div>; }

function AgentGraph({ run, selected, onSelect }) {
  const running = run?.status === 'running';
  return <div className="graph">
    <svg className="connections" viewBox="0 0 1000 440" preserveAspectRatio="none" aria-hidden="true">
      <defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="currentColor"/></marker></defs>
      <path className={running ? 'flow' : ''} d="M360 130 V177 H150 V222 M360 177 H410 V222 M360 177 H670 V222" markerEnd="url(#arrow)"/>
      <path className={`report-line ${running ? 'flow' : ''}`} d="M670 332 V385 H884 V90 H620" markerEnd="url(#arrow)"/>
      <path className={`report-line ${running ? 'flow' : ''}`} d="M150 332 V385 H670 M410 332 V385"/>
      <path className={running ? 'flow' : ''} d="M250 281 H300 M510 281 H560" markerEnd="url(#arrow)"/>
    </svg>
    <span className="graph-label command-label">ASSIGN / REVIEW</span><span className="graph-label reporting-label">CONTINUOUS REPORTING</span>
    {roles.map(r => { const a = run?.agents[r.id]; const Icon = r.icon; return <button key={r.id} className={`agent-node node-${r.id} ${selected === r.id ? 'selected' : ''} ${a?.status === 'working' ? 'working' : ''}`} onClick={() => onSelect(r.id)}>
      <div className="node-top"><span className="node-icon"><Icon size={19}/></span><span className="node-number">AGENT {r.number}</span><span className={`status-light ${a?.status || 'idle'}`} title={a?.status || 'idle'}/></div>
      <strong>{r.name}</strong><span className="node-role">{r.role}</span><div className="node-bottom">{a?.status === 'working' ? <Loader2 size={12} className="spin"/> : a?.status === 'done' ? <Check size={12}/> : <span className="tiny-square"/>}<span>{a ? label(a.status) : 'Standing by'}</span>{a?.outputChars > 0 && <span className="node-chars">{(a.outputChars / 1000).toFixed(1)}k chars</span>}</div>
    </button>; })}
    <div className="graph-key"><span><i/>Task handoff</span><span><i className="dashed"/>Supervisor feedback</span></div>
  </div>;
}

function App() {
  const [config, setConfig] = useState({ model: 'gpt-5-nano', configured: true, ownerRequired: hosted });
  const [run, setRun] = useState(null); const [runs, setRuns] = useState([]);
  const [selected, setSelected] = useState('boss'); const [tab, setTab] = useState('applications');
  const [goal, setGoal] = useState(initialGoal); const [projectCount, setProjectCount] = useState(2);
  const [sources, setSources] = useState(['greenhouse', 'lever']); const [jobUrls, setJobUrls] = useState('');
  const [showSetup, setShowSetup] = useState(false); const [busy, setBusy] = useState(false);
  const [error, setError] = useState(''); const [connected, setConnected] = useState(false);
  const [modal, setModal] = useState(null); const [owner, setOwner] = useState(Boolean(token()));
  const [ownerInput, setOwnerInput] = useState(''); const [showOwner, setShowOwner] = useState(false);
  const [pending, setPending] = useState(false); const [copied, setCopied] = useState(false);
  const selectedRun = useRef(null); const latestRun = useRef(null);
  useEffect(() => {
    let disposed = false;
    const refresh = async () => { try {
      const [settings, history, state] = await Promise.all([api('config'), api('runs'), api('state', { params: selectedRun.current ? { id: selectedRun.current } : {} })]);
      if (!disposed) { setConfig(settings); setRuns(history); setRun(state); latestRun.current = state?.id; setConnected(true); if (state?.status === 'running') setPending(false); }
    } catch (e) { if (!disposed) { setConnected(false); setError(e.message); } } };
    refresh(); const interval = setInterval(refresh, hosted ? 5000 : 12000);
    let stream;
    if (!hosted) { stream = new EventSource('/api/events'); stream.addEventListener('state', e => { const state = JSON.parse(e.data); if (!selectedRun.current || selectedRun.current === state.id) { setRun(state); latestRun.current = state.id; } setConnected(true); }); stream.onerror = () => setConnected(false); }
    return () => { disposed = true; clearInterval(interval); stream?.close(); };
  }, []);
  async function launch(e) {
    e.preventDefault(); setBusy(true); setError('');
    try { const next = await api('runs', { method: 'POST', body: JSON.stringify({ goal, projectCount, sources, jobUrls: jobUrls.split('\n').map(s => s.trim()).filter(Boolean) }) }); selectedRun.current = null; if (next.id) setRun(next); else setPending(true); setShowSetup(false); }
    catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function stopWork() { setBusy(true); try { await stop(run?.id); setPending(false); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  async function viewFile(file) { setModal({ type: 'file', title: file.path, text: 'Loading…' }); try { const r = await fetch(artifactUrl(run.id, file.path)); if (!r.ok) throw new Error('File unavailable'); setModal({ type: 'file', title: file.path, text: await r.text() }); } catch(e) { setModal({ type: 'file', title: file.path, text: e.message }); } }
  async function selectRun(id) { selectedRun.current = id || null; try { setRun(await api('state', { params: id ? { id } : {} })); } catch(e) { setError(e.message); } }
  const active = run?.status === 'running' || run?.status === 'stopping' || pending;
  const currentAgent = roles.find(r => r.id === selected); const agent = run?.agents[selected];
  const ready = run?.projects.filter(p => p.status === 'ready').length || 0;
  const canControl = !config.ownerRequired || owner;
  const files = run?.artifacts.filter(a => a.kind !== 'preview') || [];
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href={hosted ? '/365-days' : '/'}><span className="brand-mark"><Workflow size={21}/></span>recruiter<span className="brand-dot">.ai</span></a><div className="top-context"><span className="day-tag">DAY 004</span><span className="muted">365 days of showing up</span></div><div className="top-links"><a href="https://github.com/rawmware/recruiter.ai" target="_blank" rel="noreferrer"><Github size={16}/><span>Source</span><ArrowUpRight size={13}/></a><span className={`connection ${connected ? 'online' : ''}`}><i/>{connected ? 'Connected' : 'Connecting'}</span>{config.ownerRequired && <button className="icon-button" aria-label="Owner controls" onClick={() => setShowOwner(true)}><LockKeyhole size={16}/></button>}</div></header>
    <main>
      <section className="page-heading"><div><div className="eyebrow"><span className="short-line"/>AN AUTONOMOUS PROOF OF WORK</div><h1>From hiring signals.<br/><span>To working software.</span></h1><p>Five agents. Two levels of oversight. Watch real job demand become applications you can actually use.</p></div><div className="mission-control"><span className="mono subtle">MISSION CONTROL / 01</span><button className="primary" onClick={() => setShowSetup(true)} disabled={active}><Play size={16} fill="currentColor"/>{pending ? 'Starting team…' : 'Launch a mission'}</button><span className="model-label"><CircleDot size={12}/>{config.model} <span>× 5 agents</span></span></div></section>
      {error && <div className="notice error" role="alert">{error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={16}/></button></div>}
      {run?.error && <div className="notice error">{run.error}</div>}
      {pending && <div className="notice"><Loader2 className="spin" size={16}/>Mission queued on GitHub Actions. This page will update when the runner starts.</div>}
      <section className="workspace-grid">
        <div className="orchestration-panel panel"><div className="panel-heading"><div><Workflow size={16}/><h2>Agent orchestration</h2><span className="small-pill">LIVE WORKFLOW</span></div><span className="mono phase">{run?.phase || 'Ready for a mission'}</span></div>
          <AgentGraph run={run} selected={selected} onSelect={setSelected}/>
          <div className="agent-inspector"><div className="inspector-title"><span className="mono subtle">{currentAgent.number}</span><strong>{currentAgent.name}</strong><Badge value={agent?.status || 'idle'}/></div><p>{agent?.task && agent.task !== 'Awaiting assignment' ? agent.task : currentAgent.description}</p><div className="inspector-meta"><span>{agent?.calls || 0} agent calls</span><span>{agent?.outputChars?.toLocaleString() || 0} output characters</span><span>{agent?.updatedAt ? `Updated ${time(agent.updatedAt)}` : 'Waiting for assignment'}</span></div></div>
        </div>
        <aside className="activity-panel panel"><div className="panel-heading"><div><Radio size={16}/><h2>Live activity</h2></div><span className="mono subtle">{run?.events.length || '00'}</span></div><div className="activity-list" aria-live="polite" aria-relevant="additions">
          {!run?.events.length ? <div className="activity-intro"><span className="terminal-symbol">&gt;_</span><h3>The team is standing by.</h3><p>Launch a mission to see real assignments, source checks, reports, and builds appear here.</p><div className="waiting-line"><i/>Awaiting first event<span className="cursor">_</span></div></div> : [...run.events].reverse().slice(0, 70).map(e => <article key={e.id} className={`activity-event kind-${e.kind}`}><div className="event-meta"><span className={`event-dot agent-${e.agent}`}/><strong>{roles.find(r => r.id === e.agent)?.name || e.agent}{e.to && <><span className="event-arrow"> → </span>{roles.find(r => r.id === e.to)?.name}</>}</strong><time>{time(e.at)}</time></div><p>{e.message}</p><span className="event-kind">{e.kind}</span></article>)}
        </div><div className="activity-footer"><Activity size={13}/>{hosted ? 'Runner updates every 15 seconds' : 'Events streamed directly from the agents'}</div></aside>
      </section>
      <section className="metrics"><div><span className="metric-number">{String(run?.jobs.length || 0).padStart(2,'0')}</span><span>Job postings read<Search size={15}/></span></div><div><span className="metric-number">{String(run?.signals.length || 0).padStart(2,'0')}</span><span>Hiring signals found<CircleDot size={15}/></span></div><div><span className="metric-number">{String(run?.artifacts.filter(a=>a.kind==='brief').length || 0).padStart(2,'0')}</span><span>Project briefs written<FileText size={15}/></span></div><div><span className="metric-number accent">{String(ready).padStart(2,'0')}</span><span>Applications ready<Layers3 size={15}/></span></div></section>
      <section className="output-section"><div className="output-heading"><div className="tabs" role="tablist" aria-label="Run outputs">{[['applications','Applications',Layers3],['signals','Hiring signals',Search],['files','Project files',FileCode2],['reports','Oversight',ShieldCheck]].map(([id,name,Icon])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{name}{id==='applications'&&<span>{run?.projects.length || 0}</span>}</button>)}</div><div className="run-controls">{active && canControl && <button className="stop" onClick={stopWork} disabled={busy}><Square size={12}/>Stop</button>}<select aria-label="Run history" value={selectedRun.current || ''} onChange={e=>selectRun(e.target.value)}><option value="">Latest mission</option>{runs.map(r=><option key={r.id} value={r.id}>{new Date(r.startedAt).toLocaleDateString()} · {r.goal.slice(0,32)} · {r.status}</option>)}</select></div></div>
      {run && <div className="run-caption"><span>{run.goal}</span><Badge value={run.status}/></div>}
      {tab==='applications' && (run?.projects.length ? <div className="project-grid">{run.projects.map((p,i)=><article className="project-card" key={p.id}><div className="project-top"><span className="project-index">0{i+1} / BUILT FROM DEMAND</span><Badge value={p.status}/></div><div className="project-visual">{p.previewUrl ? <iframe src={previewUrl(run.id,p.id)} title={`${p.name} thumbnail`} sandbox="allow-scripts allow-downloads" loading="lazy" tabIndex={-1}/> : <div className="build-placeholder"><Code2 size={32}/><span>{p.status==='queued'?'Brief ready. Build queued.':p.status==='failed'?'Build needs attention.':'Building this application…'}</span></div>}</div><div className="project-content"><h3>{p.name}</h3><p>{p.summary}</p><div className="project-signals">{p.signalTitles.map(s=><span key={s}>{s}</span>)}</div>{p.tests && <div className="test-summary"><ShieldCheck size={14}/>{p.tests.results.filter(t=>t.passed).length}/{p.tests.results.length} checks passed · {p.attempts} build attempt{p.attempts!==1?'s':''}</div>}<div className="project-actions"><button disabled={!p.previewUrl} onClick={()=>setModal({type:'preview',title:p.name,project:p})}>Open application<ArrowUpRight size={16}/></button><button className="text-button" onClick={()=>viewFile({path:`briefs/${p.id}.md`})}><FileText size={14}/>Brief</button></div></div></article>)}</div> : <Empty title="The next application starts with a real need.">Your agents will turn hiring signals into project briefs, then build and test every application here.</Empty>)}
      {tab==='signals' && (run?.signals.length ? <div className="signals-grid">{run.signals.map((s,i)=><article className="signal-card" key={s.title}><span className="mono subtle">SIGNAL {String(i+1).padStart(2,'0')} · {s.type==='explicit_preference'?'EXPLICIT PREFERENCE':'INFERRED OUTCOME'}</span><h3>{s.title}</h3><p>{s.preference}</p><div className="demonstration"><Code2 size={15}/><span>{s.demonstration}</span></div>{s.evidence.map((e,j)=>{const job=run.jobs.find(job=>job.id===e.jobId);return <blockquote key={j}><p>“{e.quote}”</p><a href={job?.url} target="_blank" rel="noreferrer">{job?.company} · {job?.title}<ExternalLink size={12}/></a></blockquote>;})}</article>)}</div> : <Empty icon={Search} title="Evidence before assumptions.">Each signal will include an exact excerpt and a link to the real job posting. Inferred outcomes are clearly labeled.</Empty>)}
      {tab==='files' && (files.length ? <div className="file-list">{files.map(f=><button key={f.path} onClick={()=>viewFile(f)}><FileText size={18}/><span>{f.path}</span><span className="file-kind">{f.kind}</span><span className="file-size">{(f.bytes/1024).toFixed(1)} KB</span><ArrowUpRight size={15}/></button>)}</div> : <Empty icon={FileText} title="A paper trail for every build.">Research, Markdown briefs, application source, and test reports appear here as the agents write them.</Empty>)}
      {tab==='reports' && <div className="oversight-grid"><div><h3>Supervisor → Boss</h3>{run?.reports.length ? [...run.reports].reverse().map((r,i)=><article className="report" key={i}><div><time>{time(r.at)}</time><Badge value={r.recommendation}/></div><p>{r.summary}</p>{r.concerns.map(c=><p className="concern" key={c}>{c}</p>)}</article>):<p className="muted">The supervisor reports on activity, artifacts, and test results throughout the mission.</p>}</div><div><h3>Boss decisions</h3>{run?.decisions.length ? [...run.decisions].reverse().map((r,i)=><article className="report" key={i}><div><strong>{r.subject}</strong><Badge value={r.decision}/></div><p>{r.message}</p>{r.instructions&&<p className="muted">{r.instructions}</p>}</article>):<p className="muted">The boss reviews each handoff and decides whether to accept, revise, or stop.</p>}</div></div>}
      </section>
      <footer><span><span className="footer-logo">r.ai</span>Built by Roman Cottonham · Day 004</span><span>{run ? `${run.usage.calls} agent calls · ${(run.usage.input+run.usage.output).toLocaleString()} tokens`:'Real sources. Real artifacts. Visible accountability.'}</span><a href="https://rawmware.com/365-days">The other 364 days<ArrowUpRight size={14}/></a></footer>
    </main>
    {showSetup && <div className="modal-backdrop" onClick={()=>setShowSetup(false)}><section className="modal setup-modal" role="dialog" aria-modal="true" aria-labelledby="setup-title" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close mission setup" onClick={()=>setShowSetup(false)}><X/></button><div className="eyebrow">GIVE THE TEAM A DIRECTION</div><h2 id="setup-title">Launch a mission.</h2><p>The boss assigns the work. The team researches, writes briefs, and builds every project.</p><form onSubmit={launch}><label>What should the team investigate?<textarea autoFocus value={goal} onChange={e=>setGoal(e.target.value)} minLength={12} maxLength={1200} required rows={4}/></label><div className="setup-row"><label>Applications to build<select value={projectCount} onChange={e=>setProjectCount(Number(e.target.value))}>{[1,2,3].map(n=><option value={n} key={n}>{n} application{n>1?'s':''}</option>)}</select></label><div><span className="form-label">Agent model</span><span className="model-box">{config.model}</span></div></div><fieldset><legend>Read public job boards</legend><div className="source-options">{[['greenhouse','Greenhouse'],['lever','Lever'],['remotive','Remotive']].map(([id,name])=><label key={id}><input type="checkbox" checked={sources.includes(id)} onChange={e=>setSources(e.target.checked?[...sources,id]:sources.filter(s=>s!==id))}/>{name}</label>)}</div></fieldset><label>Specific job links <span className="muted">optional · one per line</span><textarea value={jobUrls} onChange={e=>setJobUrls(e.target.value)} rows={2} placeholder="https://www.indeed.com/viewjob?jk=…"/></label><p className="form-note">Indeed, Greenhouse, Lever, Ashby, and Remotive links are supported where posting data is accessible. Up to 3 apps, 3 build attempts per app, and 38 agent calls per mission.</p><button className="primary" type="submit" disabled={busy || !config.configured || !canControl}>{busy?<Loader2 size={16} className="spin"/>:<Play size={16}/>}Start the team</button>{hosted && <div className="github-launch"><p>Run the team using your GitHub account. Copy this mission, open the workflow, then paste it into the mission field and select Run workflow.</p><button type="button" className="text-button" onClick={async()=>{await navigator.clipboard.writeText(JSON.stringify({goal,projectCount,sources,jobUrls:jobUrls.split('\n').map(s=>s.trim()).filter(Boolean)}));setCopied(true);}}>{copied?'Mission copied':'Copy mission'}</button><a href="https://github.com/rawmware/recruiter.ai/actions/workflows/mission.yml" target="_blank" rel="noreferrer">Run on GitHub <ArrowUpRight size={14}/></a><button className="text-button" type="button" onClick={()=>{setShowSetup(false);setShowOwner(true);}}>Or connect owner controls</button></div>}{!config.configured&&<p role="alert">Server credentials are not configured.</p>}</form></section></div>}
    {showOwner && <div className="modal-backdrop"><section className="modal setup-modal" role="dialog" aria-modal="true" aria-labelledby="owner-title"><button className="modal-close" aria-label="Close owner controls" onClick={()=>setShowOwner(false)}><X/></button><LockKeyhole size={24}/><h2 id="owner-title">Owner controls</h2><p>Everyone can watch. To start missions from this page, use a GitHub token with Actions write access to recruiter.ai. It is kept only in this tab and sent to GitHub through the website.</p><form onSubmit={e=>{e.preventDefault();sessionStorage.setItem('recruiter-owner',ownerInput);setOwner(true);setShowOwner(false);setShowSetup(true);}}><label>GitHub access token<input type="password" autoFocus value={ownerInput} onChange={e=>setOwnerInput(e.target.value)} required/></label><button className="primary">Unlock this tab</button>{owner&&<button type="button" className="text-button" onClick={()=>{sessionStorage.removeItem('recruiter-owner');setOwner(false);setShowOwner(false);}}>Lock controls</button>}</form></section></div>}
    {modal && <div className="modal-backdrop" onClick={()=>setModal(null)}><section className={`modal artifact-modal ${modal.type==='preview'?'preview-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="artifact-title" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="mono subtle">{modal.type==='preview'?'WORKING APPLICATION':'PROJECT ARTIFACT'}</span><h2 id="artifact-title">{modal.title}</h2></div><button aria-label="Close artifact" onClick={()=>setModal(null)}><X/></button></div>{modal.type==='preview'?<><div className="preview-info"><ShieldCheck size={14}/>{modal.project.tests?.passed?'Browser checks passed':'Preview available · checks need attention'}<a href={previewUrl(run.id,modal.project.id)} target="_blank" rel="noreferrer">Open full screen<Maximize2 size={14}/></a></div><iframe title={modal.title} src={previewUrl(run.id,modal.project.id)} sandbox="allow-scripts allow-downloads"/></>:<><a className="download-link" href={artifactUrl(run.id,modal.title)} download={modal.title.split('/').pop()}>Download file<ArrowDownLeft size={14}/></a><pre>{modal.text}</pre></>}</section></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
